### ISSUE TITLE
Pipelines should be a directed (acyclic?) graph

### ISSUE THREAD

**Issue by cbeer** [pipeline-project/scada#1]
Steps are currently linearly ordered. Instead, steps should form a graph, allowing data managers to connect arbitrary step input and output points together.

This will also allow arbitrary splitting, so an output can be routed to multiple steps.

After finishing this ticket, we will need to create tools for merging streams back together.

**Comment by cbeer** [comment]
I'm tempted to take this off the table. We could probably fake this reasonable well with a component that can copy another component, and some fancy UI tricks.

```
   a
 /    \
b     c
 \    /
   d
```

Can be treated as:

```
a -> b -> d
a -> c -> d
```

**Comment by mejackreed** [comment]
:+1: for simplicity
